sudo: false
language: python
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "pypy"
addons:
  apt:
    packages:
        libcups2-dev
install: pip install tox-travis
script: tox -v
